samoloty/config/routes.rb
Samochody::Application.routes.draw do
  get "sessions/new"

  get "sessions/create"

  get "sessions/failure"

  resources :fortunes

	root :to => 'fortunes#index'
get '/logout', :to => 'sessions#destroy'
	get   '/login', :to => 'sessions#new', :as => :login
	match '/auth/:provider/callback', :to => 'sessions#create'
	match '/auth/failure', :to => 'sessions#failure'
	match '/signout' => 'sessions#destroy', :as => :signout
end

samoloty/app/models/authorization.rb
class Authorization < ActiveRecord::Base
  attr_accessible :provider, :uid, :user
  belongs_to :user
  validates :provider, :uid, :presence => true
  #validates_presence_of :user_id, :uid, :provider
  #validates_uniqueness_of :uid, :scope => :provider
  
  #def self.find_from_hash(hash)
  # find_by_provider_and_uid(hash['provider'], hash['uid'])
  #end
  #
  #def self.create_from_hash(hash, user = nil)
  # user ||= User.create_from_hash!(hash)
  # Authorization.create(:user => user, :uid => hash['uid'], :provider => hash['provider'])
  #end
  
  def self.find_or_create(auth_hash)
    unless auth = find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      user = User.create :name => auth_hash["info"]["name"], :email => auth_hash["info"]["email"]
      auth = create :user => user, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    end
    auth
  end
  
end

samoloty/app/models/fortune.rb
class Fortune < ActiveRecord::Base
  attr_accessible :quotation, :source, :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :storage => :filesystem
end

samoloty/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :name
	has_many :authorizations
	validates :name, :email, :presence => true
def add_provider(auth_hash)
  # Check if the provider already exists, so we don't add it twice
  unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
  end
end
end

samoloty/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

samoloty/app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
 

  # GET /fortunes
  # GET /fortunes.json
  def index
    @fortunes = Fortune.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fortunes }
    end
  end

  # GET /fortunes/1
  # GET /fortunes/1.json
  def show
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/new
  # GET /fortunes/new.json
  def new
    @fortune = Fortune.new( params[:fortune] )

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  # POST /fortunes.json
  def create
    #@fortune = Fortune.new(params[:fortune])
	  @fortune = Fortune.create( params[:fortune] )
    respond_to do |format|
      if @fortune.save
        format.html { redirect_to @fortune, notice: 'Fortune was successfully created.' }
        format.json { render json: @fortune, status: :created, location: @fortune }
      else
        format.html { render action: "new" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fortunes/1
  # PUT /fortunes/1.json
  def update
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      if @fortune.update_attributes(params[:fortune])
        format.html { redirect_to @fortune, notice: 'Fortune was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fortunes/1
  # DELETE /fortunes/1.json
   def destroy
    @fortune = Fortune.find(params[:id])
    @fortune.destroy

    redirect_to fortunes_path
  end

end

samoloty/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth_hash = request.env['omniauth.auth']
    if session[:user_id]
      # Means our user is signed in. Add the authorization to the user
      User.find(session[:user_id]).add_provider(auth_hash)
      redirect_to root_url
	
    else
      # Log him in or sign him up
      auth = Authorization.find_or_create(auth_hash)
      # Create the session
      session[:user_id] = auth.user.id
      redirect_to root_url

	
    end
  end
  
  def destroy
    session[:user_id] = nil
    
	redirect_to root_url
  end
  
  def failure
    render :text => "Sorry, but you didn't allow access to our app!"
  end
  
  def auth_hash
    request.env['omniauth.auth']
  end
  


end

samoloty/app/helpers/application_helper.rb
module ApplicationHelper
end

samoloty/app/helpers/fortunes_helper.rb
module FortunesHelper
end

samoloty/app/helpers/sessions_helper.rb
module SessionsHelper
end

samoloty/app/views/fortunes/_form.html.erb
<%= simple_form_for @fortune, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.file_field :avatar %>
  <%= f.input :quotation, :label => "Name",:input_html => { :rows => 8, :cols => 80 } %>
   <%= f.input :source, :label => "Country" %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                fortunes_path, :class => 'btn' %>
  </div>
<% end %>

samoloty/app/views/fortunes/edit.html.erb
<%- model_class = Fortune -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit aircraft") %></h1>
</div>
<%= image_tag @fortune.avatar.url :medium %>
<%= render :partial => 'form' %>

samoloty/app/views/fortunes/index.html.erb
<%- model_class = Fortune -%>
<div class="page-header">
  <h1><%=t '.title', :default => "All aircraft" %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Avatar</th>
      
      <th>ID</th>
      <th>Name aircraft</th>
      <th>Country</th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fortunes.each do |fortune| %>
      <tr>
        <td><%= image_tag(fortune.avatar.url :thumb) if fortune.avatar? %></td>
        <td><%= link_to fortune.id, fortune_path(fortune) %></td>
        <td><%= fortune.quotation %></td>
        <td><%= fortune.source %></td>
        <td><%=l fortune.created_at %></td>
        <td>
		<% if current_user %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_fortune_path(fortune), :class => 'btn btn-mini' %>
         <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      fortune_path(fortune),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
					
		
		<% end %>
	   </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_fortune_path,
            :class => 'btn btn-primary' %>
<% end %>

samoloty/app/views/fortunes/new.html.erb
<%- model_class = Fortune -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New aircraft") %></h1>
</div>

<%= render :partial => 'form' %>

samoloty/app/views/fortunes/show.html.erb
<%- model_class = Fortune -%>
<div class="page-header">
  <h1><%=t '.title', :default => "aircraft" %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:quotation) %>:</strong></dt>
  <dd><%= @fortune.quotation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:source) %>:</strong></dt>
  <dd><%= @fortune.source %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              fortunes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_fortune_path(@fortune), :class => 'btn' %>
  <%= link_to t('.destroy',),
              fortune_path(@fortune),
              :method => 'destroy',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
			  
<%= image_tag @fortune.avatar.url %>
</div>

samoloty/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	
    <title><%= content_for?(:title) ? yield(:title) : "Samoloty" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
	
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'aircrafts', fortunes_path, :class => 'brand' %>
          <div class="provider pull-right">
            <ul class="nav">
            
              <li><% if current_user %>
  Welcome <%= current_user.name %>!<% end %></li>
              
			  <li>

<% if current_user %>
   <%= link_to "Logout With Facebook", "/signout" %>
  
<% else %>

 
  <%= link_to "Connect With Facebook", "/auth/facebook" %>
<% end %>

</li>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container" id="container">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
          <div class="span3">
            
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

<%= javascript_include_tag "application" %>
  </body>
</html>

samoloty/app/views/layouts/fixed.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Samochody" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Samochody</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>